### ISSUE TITLE
Replace ReUnit with infinite-jest

### ISSUE THREAD

**Issue by glennsl** [facebookincubator/immutable-re#88]
The API is very similar, so there shouldn't be too much work to convert. Would you like me to give it a shot, or would you like to try it yourself?

**Comment by bordoley** [comment]
have you published npm/opam packages?

**Comment by glennsl** [comment]
No, not yet. I figured we should try it out in a branch first, to see how it works out.

**Comment by glennsl** [comment]
I think it also needs bs master to be able to use bs-dev-dependencies
